# -*- coding: utf-8 -*-
"""agentic-rag-adk-qdrant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n__eGifIhMCzrT3Fz25iX2pMNBVoeFBs
"""

!pip install langchain-community langchain opik
!pip install fastembed langchain_qdrant pypdfium2
!pip install duckduckgo-search ddgs

"""## Setup Credentials

- [Qdrant API Key and URL](https://cloud.qdrant.io/signup?utm_medium=referral&utm_source=stars&utm_campaign=devrel&utm_content=tarun-jain)
"""

import os
from google.colab import userdata

os.environ['GEMINI_API_KEY'] = "AIzaSyB93KRWGZlBE0ydi9lRAraeuMveiExjotU"
QDRANT_URL = "https://42095953-5eb2-4bad-8c51-3a9ff07f3fbb.sa-east-1-0.aws.cloud.qdrant.io:6333"
QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.BTnnenKYClre5L0Ad_UbQhIM1fgHb9dEN4Cd_9DDthY"

"""## Document Processing"""

!wget https://data.imf.org/-/media/iData/External-Storage/Documents/7FC05452C6C743D2BFB6188D2E248A38/en/2025-FAS-Annual-Report.pdf -O annual_report.pdf

from langchain_community.document_loaders import PyPDFium2Loader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import FastEmbedEmbeddings
from langchain_qdrant import QdrantVectorStore
from qdrant_client import QdrantClient, models

path = "annual_report.pdf"
loader = PyPDFium2Loader(path)
docs = loader.load()

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size = 1536, # 1024
    chunk_overlap = 0,
)
chunks = text_splitter.split_documents(docs)

"""### Index your data"""

embeddings = FastEmbedEmbeddings(model_name="jinaai/jina-embeddings-v2-small-en")

len(embeddings.embeded_query("2"))  #dense vector

collection_name = "fas-report"



client = QdrantClient(url=QDRANT_URL, api_key=QDRANT_API_KEY)

client.create_collection(
    collection_name = collection_name,
    vectors_config = {
        "dense": models.VectorParams(
            size = 512,
            distance = models.Distance.COSINE
    )})

db = QdrantVectorStore(
    client = client,
    collection_name = collection_name,
    embedding = embeddings,
    vector_name = "dense"
)

from uuid import uuid4
uuids = [str(uuid4()) for _ in range(len(chunks))]

db.add_documents(documents=chunks, ids=uuids)  #just ones

query = "projected reach of the digital remittance market by 2034"

relevant_docs = db.similarity_search(query) # k = 4
# or
retriever = db.as_retriever(search_type="mmr",search_kwargs = {"k":3})
relevant_docs2 = retriever.invoke(query)

print(len(relevant_docs))
#print(relevant_docs[0])

def retrieve_docs(query:str) -> str:
  """
  retrieve relevant document from the knowledge base. use retrieve_docs function to get the results

  Args:
      query: user prompt to retrieve the context
  """
  response = retriever.invoke(query)
  context = [docs.page_content for docs in response]

  return "\n".join(context) # string

retrieve_docs(query)

from langchain_community.tools import DuckDuckGoSearchRun

def web_search(query:str) -> str:
    """
    search results from the Google web browswer to the user query
    Args:
       query: user prompt
    """
    browse = DuckDuckGoSearchRun()
    context = browse.invoke(query)
    return context

web_search("IRAN latest updates")

"""## Multi-Agent

### Build sub agents first
"""

from google.adk.agents import LlmAgent

model_name = "gemini-2.5-flash"

knowledge_agent = LlmAgent(
    name="knowledge_base_agent",
    model=model_name,
    description="Answers questions about the Financial Annual Survey Report by retrieving relevant sections from the knowledge base.",
    instruction="""
    You are a financial research assistant with access to the Financial Annual Survey Report.

    When the user asks a question:
    1. Use the retrieve_docs tool to fetch relevant information first.
    2. Answer strictly based on what the tool returns. Do not make up numbers or facts.
    3. If the tool returns no relevant data, tell the user the information is not available in the report.
    """,
    tools=[retrieve_docs]
)

news_agent = LlmAgent(
    name="news_agent",
    model=model_name,
    description="Fetches and summarizes the latest news on any topic using DuckDuck GO Search.",
    instruction="""
    You are a news research assistant.

    When the user asks about any topic:
    1. Use the web_search tool to find the latest news.
    2. Summarize the top results clearly and concisely.
    3. Do not add opinions or information beyond what the search returns.
    """,
    tools=[web_search]
)

"""### LLM-Driven Delegation (Agent Transfer) i.e., Routing Agent"""

router = LlmAgent(
    name="router_agent",
    model=model_name,
    description="Routes user queries to the appropriate specialist agent based on the nature of the question.",
    instruction="""
    You are a routing agent. Your only job is to understand the user's query and delegate it to the right agent. Never answer yourself.

    Route to knowledge_base_agent when:
    - The question is about the Financial Annual Survey Report
    - The user asks about financials, revenue, growth, survey data, or statistics from the report

    Route to news_agent when:
    - The question is about current events, recent news, or anything happening in the world
    - The user asks about trends, market updates, or latest developments

    If the query is ambiguous, route to retrieve_docs i.e., knowledge_base_agent by default.
    Never combine both agents. Pick one and delegate immediately.
    """,
    sub_agents=[knowledge_agent, news_agent]
)

"""> Execute the Agent"""

from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService

import asyncio
from google.genai import types

import nest_asyncio
nest_asyncio.apply()

import asyncio
import logging
logging.getLogger("asyncio").setLevel(logging.CRITICAL)

APP_NAME   = "multi-agent"
USER_ID    = "tranfer_01"
SESSION_ID = "session_01"

session_service = InMemorySessionService()

session = asyncio.run(session_service.create_session(
    app_name=APP_NAME, user_id=USER_ID, session_id=SESSION_ID
))

def call_agent(query):
    runner = Runner(agent=router,
                    app_name=APP_NAME,
                    session_service=session_service)

    content = types.Content(role='user', parts=[types.Part(text=query)])

    events = runner.run(user_id=USER_ID, session_id=SESSION_ID, new_message=content)

    for event in events:
        print(f"\nDEBUG EVENT: {event}\n")
        if event.is_final_response() and event.content:
            final_answer = event.content.parts[0].text.strip()
            print("\n🟢 FINAL ANSWER\n", final_answer, "\n")

call_agent(query)

from opik.integrations.adk import OpikTracer, track_adk_agent_recursive

os.environ['OPIK_API_KEY'] = userdata.get("OPIK_API_KEY")
os.environ["OPIK_WORKSPACE"] = "tarun-r-jain"
os.environ["OPIK_PROJECT_NAME"] = "buildwithai-patna"

opik_tracer = OpikTracer(name="multi-agent")
track_adk_agent_recursive(router, opik_tracer)

def run_agent(query):
    runner = Runner(agent=router,
                    app_name=APP_NAME,
                    session_service=session_service)

    content = types.Content(role='user', parts=[types.Part(text=query)])

    events = runner.run(user_id=USER_ID, session_id=SESSION_ID, new_message=content)

    for event in events:
        if event.is_final_response() and event.content:
            return event.content.parts[0].text.strip()

run_agent(query)

run_agent("IRAN latest updates")