# -*- coding: utf-8 -*-
"""Copy of adk_build_with_ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HvS3SdOpzUMf8XJNFDetOfSVi21UFIDu
"""

pip install google-adk opik

"""## Get your Gemini API Keys and OPIK API KEY

- [OPIK API Key](https://www.comet.com/signup?utm_source=workshop&utm_medium=partner&utm_campaign=tarun)
- [Gemini API Key](https://aistudio.google.com/)
"""

import os
from google.colab import userdata

os.environ['GEMINI_API_KEY'] = "AIzaSyB93KRWGZlBE0ydi9lRAraeuMveiExjotU"
os.environ['OPIK_API_KEY'] = "KdE7tgw0EhHPZwcbGV1AL6k51"
os.environ["OPIK_WORKSPACE"] = "tarun-r-jain"
os.environ["OPIK_PROJECT_NAME"] = "buildwithai-patna"

"""## Getting started to Agents using Google ADK"""

import nest_asyncio
nest_asyncio.apply()

"""### LLM Agent"""

from google.adk.agents.llm_agent import LlmAgent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService

import asyncio
from google.genai import types

"""> Build the Cold Mail Agent"""

model_name = "gemini-2.5-flash"

instructions = """
    You are a cold email copywriting expert. Write cold outreach emails that feel human, direct, and worth replying to.

    Follow these rules strictly:

    1. Never use em-dashes or hyphens in any part of the email.
    2. Keep the email under 150 words. Brevity signals respect for the reader's time.
    3. Open with a personalized first line specific to the prospect or their company. Never start with "I" or a generic compliment like "I hope this finds you well."
    4. Focus on ONE clear value proposition. Do not list multiple offerings or benefits.
    5. End with a soft, low-friction call to action such as asking for a 15 minute call or a simple yes/no question. Never use pushy language like "Let me know ASAP."
"""

email_agent = LlmAgent(
    name="email_agent",
    model=model_name,
    description="Drafts cold outreach emails given a prospect's name, company, and context. Focuses on personalization, clear value proposition, and a strong call to action.",
    instruction=instructions
)

"""> Setup Runner and Session"""

APP_NAME   = "agents_workshop"
USER_ID    = "user_01"
SESSION_ID = "session_cold_email" #unique for every session at a time

session_service = InMemorySessionService() #space to host an agent


# to use an session that one exist
session = asyncio.run(session_service.create_session(
    app_name=APP_NAME, user_id=USER_ID, session_id=SESSION_ID
))

runner = Runner(agent=email_agent, app_name=APP_NAME,
                session_service=session_service)

"""> Execute the Agent"""

user_message = """
Write a cold email to sumit, Founding Engineer at Kaivid Labs.
On talking about self-improvement pipeline collaboration
"""

content = types.Content(
        role="user",
        parts=[types.Part(text=user_message)]
    )

events = runner.run(
        user_id=USER_ID,
        session_id=SESSION_ID,
        new_message=content
    )  #event will generator

for event in events:
  final_response_text = event.content.parts[0].text.strip()
  print(final_response_text)  #string

def run_agent(agent, user_message: str):
    runner = Runner(
        agent=agent,
        app_name=APP_NAME,
        session_service=session_service
    )

    content = types.Content(
        role="user",
        parts=[types.Part(text=user_message)]
    )

    events = runner.run(
        user_id=USER_ID,
        session_id=SESSION_ID,
        new_message=content
    )

    for event in events:
        if event.is_final_response():
            print(event.content.parts[0].text.strip())

run_agent(agent=email_agent, user_message=user_message)

"""### Tool usage

> In-built tool usage
"""

SESSION_ID = "session_search"

session = asyncio.run(session_service.create_session(
    app_name=APP_NAME, user_id=USER_ID, session_id=SESSION_ID
))

from google.adk.tools import google_search # in build searchh tool

search_agent = LlmAgent(
    name="search_agent",
    model=model_name,
    description="Answers questions by searching the web in real time using Google Search.",
    instruction="You are a research assistant. Use Google Search to find accurate, up to date information and answer the user's question concisely.",
    tools=[google_search]
)

user_message2 = "which 2 teams are playing the IPL 2026 opening game?"

run_agent(agent=search_agent, user_message=user_message2)

"""> Custom tool"""

SESSION_ID = "session_custom"

session = asyncio.run(session_service.create_session(
    app_name=APP_NAME, user_id=USER_ID, session_id=SESSION_ID
))

def check_inventory(product_name: str, current_stock: int, reorder_threshold: int) -> dict:
    """Checks current stock level against reorder threshold and returns stock status with reorder recommendation."""
    return {
        "product": product_name,
        "current_stock": current_stock,
        "needs_reorder": current_stock <= reorder_threshold,
        "status": "CRITICAL" if current_stock == 0 else "LOW" if current_stock <= reorder_threshold else "OK"
    }

inventory_agent = LlmAgent(
    model=model_name,
    name="inventory_agent",
    description="Monitors retail stock levels and alerts when products need reordering.",
    instruction="You are a retail inventory manager. Use the check_inventory tool to assess stock levels and give a clear reorder recommendation.",
    tools=[check_inventory]
)

run_agent(inventory_agent, """
  Check inventory for:
  Product: Nike Air Max
  Current stock: 12 units
  Reorder threshold: 20 units
""")

"""## Tracing and Monitoring your Agent using Comet OPIK"""

import opik
from opik.integrations.adk import OpikTracer, track_adk_agent_recursive

opik_tracer = OpikTracer(name="search-agent")
track_adk_agent_recursive(search_agent, opik_tracer)

run_agent(search_agent,"what is the situation in iran")

"""## What is ReAcT and Planner for the Agent Execution

planner (Optional): Assign a BasePlanner instance to enable multi-step reasoning and planning before execution. There are two main planners:

- BuiltInPlanner: Leverages the model's built-in planning capabilities (e.g., Gemini's thinking feature).
- PlanReActPlanner: This planner instructs the model to follow a specific structure in its output: first create a plan, then execute actions (like calling tools), and provide reasoning for its steps.
"""

from google.adk.planners import PlanReActPlanner

APP_NAME = "compare"
USER_ID = "user1"
SESSION_ID = "session_plan"

session = asyncio.run(session_service.create_session(
    app_name=APP_NAME, user_id=USER_ID, session_id=SESSION_ID
))

search_agent_with_planning = LlmAgent(
    name="search_agent",
    model=model_name,
    description="Answers questions by searching the web in real time using Google Search.",
    instruction="You are a research assistant. Use Google Search to find accurate, up to date information and answer the user's question concisely.",
    tools=[google_search],
    planner=PlanReActPlanner()
)

def call_agent(query):
    runner = Runner(
          agent=search_agent_with_planning,
          app_name=APP_NAME,
          session_service=session_service
      )
    content = types.Content(role='user', parts=[types.Part(text=query)])
    events = runner.run(user_id=USER_ID, session_id=SESSION_ID, new_message=content)

    for event in events:
        print(f"\nDEBUG EVENT: {event}\n")
        if event.is_final_response() and event.content:
            final_answer = event.content.parts[0].text.strip()
            print("\n🟢 FINAL ANSWER\n", final_answer, "\n")

user_message3 = "Check if Nike, Adidas, and Puma have any ongoing discounts right now"

call_agent(query=user_message3)

"""## Multi Agent workflow + Agentic RAG (knowledge base as tool using Qdrant)

> New notebook: [Agentic RAG](https://colab.research.google.com/drive/1n__eGifIhMCzrT3Fz25iX2pMNBVoeFBs?usp=sharing)

## Memory Enabled Agent using Cognee and Qdrant

> New notebook: Memory - [Cognee and Google ADK integration](https://colab.research.google.com/drive/1wtA0H5srGns6faR0mLMEvqs7RTNvien_?usp=sharing)
"""